### PR TITLE
Namespace Refactor: refactor bas into namespace

### PR DESCRIPTION
**Pull request by simondevenish**

### CODE REVIEW

**Comment by HexDecimal** [comment]
Should it be `bas`?  Or `base`?  It seems the name was unnecessarily abbreviated.  I went with `base::` for #11

**Comment by simondevenish** [comment]
> Should it be `bas`? Or `base`? It seems the name was unnecessarily abbreviated. I went with `base::` for #11

Didn't realise it was meant to be base, just assumed it was an acronym I didn't understand...hah...I will update to base

**Comment by HexDecimal** [comment]
I can't tell if it's an acronym either, which is the problem.  My best guess was the someone was too lazy to add the `e` at the end.

My assumption based on the kind of things in the folder.  Mostly features that other modules depend on.

**Comment by simondevenish** [comment]
> I can't tell if it's an acronym either, which is the problem. My best guess was the someone was too lazy to add the `e` at the end.
> 
> My assumption based on the kind of things in the folder. Mostly features that other modules depend on.

base is totally sensible and makes sense moving forward. I have updated bas to base

**Comment by HexDecimal** [comment]
Would you mind rebasing on top of the main branch to sync with it instead of merging it?

**Comment by HexDecimal** [comment]
Also removing the `bas_` prefix from the includes has already gotten very confusing.  I want to try replacing `bas_` with `base/` instead.

**Comment by simondevenish** [comment]
> Would you mind rebasing on top of the main branch to sync with it instead of merging it?

Sure, did you want me to do that for this PR or is it fine to leave as and do this moving forward?

**Comment by HexDecimal** [comment]
> Sure, did you want me to do that for this PR or is it fine to leave as and do this moving forward?

Sorry, I misunderstood the reason a file changed while reviewing the changes.  You don't have to do it now or later.

**Review by HexDecimal — APPROVED** [review]
Was that the last commit?  Looks good now.

**Comment by simondevenish** [comment]
That's the last one

**Pull request merged**
